# Generated by Django 3.0.3 on 2020-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('make', models.CharField(blank=True, max_length=300)),
                ('model', models.CharField(blank=True, max_length=300)),
                ('car_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
