# Generated by Django 3.0.3 on 2020-02-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='license_plate',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='car_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='make',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='model',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
