# Generated by Django 3.0.3 on 2020-02-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200206_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('make', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('license_plate', models.CharField(max_length=300, null=True)),
                ('car_id', models.CharField(max_length=300, null=True)),
                ('date', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
